"""add vote

Revision ID: 80ff3f0fb082
Revises: 370ba88f8d92
Create Date: 2024-07-06 13:43:38.918271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80ff3f0fb082'
down_revision: Union[str, None] = '370ba88f8d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.alter_column('posts', 'published',
        existing_type=mysql.TINYINT(display_width=1),
        type_=sa.String(length=10),
        nullable=True,
        existing_server_default=sa.text("'1'")
    )
    op.alter_column('posts', 'created_at',
        existing_type=mysql.TIMESTAMP(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text('CURRENT_TIMESTAMP')
    )
    op.alter_column('users', 'password',
        existing_type=mysql.VARCHAR(length=45),
        type_=sa.String(length=10000),
        existing_nullable=False
    )
    op.alter_column('users', 'created_at',
        existing_type=mysql.TIMESTAMP(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text('CURRENT_TIMESTAMP')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
        existing_type=sa.TIMESTAMP(),
        type_=mysql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text('CURRENT_TIMESTAMP')
    )
    op.alter_column('users', 'password',
        existing_type=sa.String(length=10000),
        type_=mysql.VARCHAR(length=45),
        existing_nullable=False
    )
    op.alter_column('posts', 'created_at',
        existing_type=sa.TIMESTAMP(),
        type_=mysql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text('CURRENT_TIMESTAMP')
    )
    op.alter_column('posts', 'published',
        existing_type=sa.String(length=10),
        type_=mysql.TINYINT(display_width=1),
        nullable=False,
        existing_server_default=sa.text("'1'")
    )
    op.drop_table('votes')
    # ### end Alembic commands ###
